global:
  ingress:
    configureCertmanager: false
    provider: "traefik"
    class: "traefik"

  hosts:
    domain: localhost
    externalIP: 127.0.0.1
  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022
installCertmanager: false
nginx-ingress:
  enabled: false

prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: NodePort
      nodePort: 32022
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
