- name: Install required packages
  hosts: '*'
  become: yes
  vars:
    docker_install_compose: false
    docker_users: ["{{ ansible_user }}"]

  pre_tasks:
    - name: Ensure packages are present
      ansible.builtin.apt:
        name:
          - curl
          - firefox-esr
          - git
          - terminator
          - xfce4
          - xfce4-goodies
          - zsh
        state: present
        update_cache: yes
      notify: Reboot the machine

  roles:
    - geerlingguy.docker
    - githubixx.kubectl
    - averagebit.k3d
    - name: geerlingguy.helm
      helm_version: "v3.18.3"
    - helmfile
    - name: ctorgalson.oh-my-zsh
      omz_user:
        name: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        settings: ""

  handlers:
    - name: Reboot the machine
      ansible.builtin.reboot:

- name: Configure user settings
  hosts: '*'
  tasks:
    - name: Ensure the user uses zsh
      become: yes
      user:
        name: "{{ ansible_user }}"
        # password: vagrant
        password: "$y$j9T$l9aju.2ll9eylQ3iZBhWf/$ooW57CPg90sGQYyEQkr9NeS2TCYe9hSRp2dajaVtKQB"
        shell: /bin/zsh
    - name: Ensure kubectl is aliased to k
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        append_newline: true
        prepend_newline: true
        block: |
          mkdir -p "${fpath[1]}"
          source <(kubectl completion zsh)
          alias k="kubectl"
          compdef _kubectl k
