- name: Install required packages
  hosts: '*'
  become: yes
  vars:
    docker_install_compose: false
    docker_users: ["{{ ansible_user }}"]

  tasks:
    - name: Ensure packages are present
      ansible.builtin.apt:
        name:
          - curl
          - firefox-esr
          - git
          - terminator
          - vagrant
          - xfce4
          - xfce4-goodies
          - zsh
        state: present
        update_cache: yes
      notify: Reboot the machine

    - name: Include vbox-guest-additions role
      ansible.builtin.include_role:
        name: vbox-guest-additions
    - name: Include geerlingguy.docker role
      ansible.builtin.include_role:
        name: geerlingguy.docker
    - name: Include githubixx.kubectl role
      ansible.builtin.include_role:
        name: githubixx.kubectl
    - name: Include averagebit.k3d role
      ansible.builtin.include_role:
        name: averagebit.k3d
    - name: Include geerlingguy.helm role
      ansible.builtin.include_role:
        name: geerlingguy.helm
      vars:
        helm_version: "v3.18.3"
    - name: Include helmfile role
      ansible.builtin.include_role:
        name: helmfile

  handlers:
    - name: Reboot the machine
      ansible.builtin.reboot:

- name: Configure user settings
  hosts: '*'

  roles:
    - name: ctorgalson.oh-my-zsh
      become: true
      omz_user:
        name: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        settings: |
          mkdir -p "${fpath[1]}"
          source <(kubectl completion zsh)
          alias k="kubectl"
          compdef _kubectl k

          alias nvim="vim"
          compdef _vim nvim
      omz_plugins:
        - git

  tasks:
    - name: Ensure the user uses zsh
      become: yes
      user:
        name: "{{ ansible_user }}"
        password: "{{ 'vagrant' | password_hash('sha512') }}"
        shell: /bin/zsh
