MASTER_NODE_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl
  SHELL

  config.vm.define "sasaicicS" do |control|
    control.vm.hostname = "sasaicicS"
    control.vm.network "private_network", ip: MASTER_NODE_IP
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sasaicicS"]
      v.memory = 2048
      v.cpus = 2
    end
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | \
      INSTALL_K3S_EXEC="server --advertise-address #{MASTER_NODE_IP}" \
      K3S_KUBECONFIG_MODE="644" sh -s -
    SHELL
  end

end
